### ISSUE TITLE
feat: toast actions

### ISSUE THREAD

**Issue by danielhe4rt** [basementdevs/kadeck#5]
The current implementation uses a simple "alert" to propagate user responses under the Tauri Actions (hooks/commands). The goal is to implement toasts for easier reuse through new hooks implementations.

* Proposals: Implementing toasts will provide a more user-friendly way to display notifications and can be reused in various hooks implementations. Reference: Shadcn Toasts.
* Next steps: Develop and integrate the toast functionality, ensuring it can be reused through new hooks implementations. Check the Shadcn Toasts for guidance.

![image](https://github.com/user-attachments/assets/1e91a80c-cd70-46e3-9376-86ce7e949d58)

Check: [Shadcn Toasts](https://ui.shadcn.com/docs/components/toast)

**Comment by Daniel-Boll** [comment]
Better than toasts there is the [sonner](https://ui.shadcn.com/docs/components/sonner)
