### ISSUE TITLE
feat: enchance development workflow

### ISSUE THREAD

**Issue by gvieira18** [basementdevs/kadeck#8]
## Summary

This issue groups several improvements and configurations to enhance the development workflow, CI pipeline and set up a code quality

- [ ] **Makefile ~~everywhere~~**
- [ ] **Dependency Management**
  - [ ] Pin rust and js deps to specific versions (no `^`)
- [ ] **Linting/Formatting**
  - **Javacript**
    - [ ] `biome`
    - [ ] `editorconfig`
  - **Rust**
    - [ ] `rustfmt`
    - [ ] `clippy`
  - **Git hooks**
    - [ ] `lefthook`
- [ ] **Pipeline**
  - [ ] Continuous Integration - CI
- [ ] **Automated Dependency Updates**
  - [ ] Dependabot or Renovate

**Comment by rosajsx** [comment]
@gvieira18, I Have a question!
 Why biome instead eslint?

**Comment by gvieira18** [comment]
> @gvieira18, I Have a question! Why biome instead eslint?

Because it's easier to configure and it's the default we use on other JS projects on basement.
